INSERT INTO FILTRI_TIPO (TIPFIL, DESFIL, FLDFIL) VALUES (20, 'POSTAZIONE', 'IDXPOS');

ALTER TABLE FILTRI
ADD IDXPOS SMALLINT;
COMMENT ON COLUMN FILTRI.IDXPOS IS
'idx della postazione nella tabella ANTENNE_POS di PROLAV';



INSERT INTO MENU (CODMNU, DESMNU, CODGRP, FLGENABLED, ICON, ORDINE, CODTIP, PAGINA, RIFMENU) VALUES ('MNUVERRFID', 'Verifica RFID', 'F', 1, 'hardware-chip-outline', 10, 'M', '/verifica-rfid', NULL);